---
- hosts: "{{ vhost | default('master') }}"

  become: yes
  become_method: sudo
  gather_facts: no


  vars_files:
    - shared_vars.yml

  tasks:
    - name: Ensure Nginx, uwsgi, git, supervisor is installed
      apt:
        force_apt_get: yes
        pkg:
          - nginx
          - git
          - uwsgi
          - python-setuptools
          - supervisor
        state: present

      tags: basic

    - name: Get updated files from git repository
      git:
        repo: https://{{ githubuser }}:{{ lookup('env','GITHUB_USER_PASS') }}@bitbucket.org/seadvocacy/drohealth-web.git
        dest: "{{ project_path }}"
        version: "{{ git_branch }}"
        force: yes
      tags: git

    - name: Remove import from .local
      tags: remove
      lineinfile:
        path: "{{ project_path }}/{{ application_name }}/settings/__init__.py"
        regexp: "^from"
        state: absent

    - name: Write the correct import
      tags: add
      lineinfile:
        path: "{{ project_path }}/{{ application_name }}/settings/__init__.py"
        line: "from .{{ settings_file }} import *"
        state: present
        create: yes

    - name: Activate Virtualenv
      tags: venv
      include: setup_django_app.yml

  # roles:
  #   - setup
  #   - deploy


  post_tasks:
      - name: Restart Nginx and uWSGi Last time
        service: name={{ item }} state=restarted
        with_items:
            - nginx
            - uwsgi
            - supervisor

      - name: Ensure Nginx and uWSGi is running
        service: name={{ item }} state=started enabled=yes
        with_items:
            - nginx
            - uwsgi
            - supervisor