---
- hosts: "{{ vhost | default('dev') }}"

  become: yes
  become_method: sudo
  gather_facts: no


  vars_files:
    - shared_vars.yml

  tasks:
    - name: Ensure Nginx and uwsgi and git is installed
      apt:
        force_apt_get: yes
        pkg:
          - nginx
          - git
          - uwsgi
          - python-setuptools
        state: present

      tags: basic

    - name: Get updated files from git repository
      git:
        repo: https://{{ githubuser }}:{{ lookup('env','GITHUB_USER_PASS') }}@bitbucket.org/seadvocacy/drohealth-web.git
        dest: "{{ project_path }}"
        version: "{{ git_branch }}"
        force: yes
      tags: git
    - name: Activate Virtualenv 
      tags: venv
      include: setup_django_app.yml

  # roles:
  #   - setup
  #   - deploy


  post_tasks:
      - name: Restart Nginx and uWSGi Last time
        service: name={{ item }} state=restarted
        with_items:
            - nginx
            - uwsgi

      - name: Ensure Nginx and uWSGi is running
        service: name={{ item }} state=started enabled=yes
        with_items:
            - nginx
            - uwsgi